### ISSUE TITLE
Users page

### ISSUE THREAD

**Issue by BUI-studies** [BUI-studies/yidlorama#30]
Based on the component `UniversalTable` build a page with the list of all users. 
The page should be accessible only to `ADMIN`. 

![Image](https://github.com/BUI-studies/yidlorama/assets/104223028/fda0bc58-7814-43ea-ba6e-1bd5bcd7317a)

**Comment by AKot1988** [comment]
![Image](https://github.com/BUI-studies/yidlorama/assets/113294189/ea0420b1-28bb-4a7a-8f28-92c9fa4967fe)

Users page view.

For solution, wich will be render users Data from real database and make acsessible this page for admin role only i need acsess to db, to create some functions
