### ISSUE TITLE
Features for creating a new user

### ISSUE THREAD

**Issue by AKot1988** [BUI-studies/yidlorama#35]
![Image](https://github.com/user-attachments/assets/35a810c4-b9b9-4225-997a-9b56805b9255)

The button "1" should have the ability to trigger the functionality for creating a new user, either through a modal window or by opening a new page (which would be more appropriate to attach an action to this page).

**Comment by BUI-studies** [comment]
look at the files of the router. 
it was refreshed and now we have new common route which looks like this:
```
{
	path: COMMON_ROUTES_NAMES.ORDERS,
	element: <Orders />,
	children: [
		{
			path: COMMON_ROUTES_NAMES.CREATE_ORDER,
			element: <h2>New Order</h2>,
		},
	],
},
```

use this structure as an example to make "Create User" page. this structure in routes are mandatory from now on.

**Comment by BUI-studies** [comment]
blocked by - https://github.com/BUI-studies/yidlorama/issues/38
